version: "3"
services:
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
        ports:
            - 9200:9200
        environment:
            - node.name=es01
            - discovery.type=single-node
        volumes:
            - data01:/usr/share/elasticsearch/data
        networks:
            - elastic

    kib01:
        image: docker.elastic.co/kibana/kibana:7.17.0
        container_name: kib01
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: '["http://es01:9200"]'
        networks:
            - elastic

volumes:
    data01:
        driver: local

networks:
  elastic:
    driver: bridge